### ISSUE TITLE
C++ buildproblems with arm-none-eabi-g++ v6

### ISSUE THREAD

**Issue by OlegHahm** [RIOT-OS/Release-Specs#28]
Building for ARM-Cortex platforms currently fails for me with:
```
arm-none-eabi-g++ \
        -DRIOT_FILE_RELATIVE=\"tests/cpp11_condition_variable/main.cpp\" \
        -DRIOT_FILE_NOPATH=\"main.cpp\" \
        -Werror -mcpu=cortex-m3 -mlittle-endian -mthumb -mfloat-abi=soft -mno-thumb-interwork -ffunction-sections -fdata-sections -fno-builtin -fshort-enums -ggdb -g3 -Os -fno-delete-null-pointer-checks -Werror=strict-prototypes -Werror=old-style-definition -fno-common -Wall -include '/home/oleg/git/RIOT/tests/cpp11_condition_variable/bin/cc2538dk/riotbuild/riotbuild.h' -std=c++11 -isystem /usr/arm-none-eabi/include/nano -isystem /usr/arm-none-eabi/include -I/home/oleg/git/RIOT/core/include -I/home/oleg/git/RIOT/drivers/include -I/home/oleg/git/RIOT/sys/include -I/home/oleg/git/RIOT/cpu/cc2538/include -I/home/oleg/git/RIOT/boards/cc2538dk/include -I/home/oleg/git/RIOT/cpu/cortexm_common/include -I/home/oleg/git/RIOT/sys/libc/include -I/home/oleg/git/RIOT/sys/cpp11-compat/include  -MD -MP -c -o /home/oleg/git/RIOT/tests/cpp11_condition_variable/bin/cc2538dk/cpp11_condition_variable/main.o /home/oleg/git/RIOT/tests/cpp11_condition_variable/main.cpp
In file included from /usr/arm-none-eabi/include/c++/6.2.0/ext/string_conversions.h:41:0,
                 from /usr/arm-none-eabi/include/c++/6.2.0/bits/basic_string.h:5402,
                 from /usr/arm-none-eabi/include/c++/6.2.0/string:52,
                 from /home/oleg/git/RIOT/tests/cpp11_condition_variable/main.cpp:21:
/usr/arm-none-eabi/include/c++/6.2.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
```
However:
```
`# ls -lah /usr/arm-none-eabi/include/c++/6.2.0/stdlib.h
-rw-r--r-- 1 root root 2.2K Aug 31 19:52 /usr/arm-none-eabi/include/c++/6.2.0/stdlib.h
```

**Comment by OlegHahm** [comment]
> @OlegHahm I can compile the cpp11_condition_variable test without issues for the samr21-xpro using compiler version 5.4.1. However, my stdlib.h file has a different location:
>
> $ find . -name "stdlib.h"
> arm-none-eabi/include/c++/5.4.1/tr1/stdlib.h
> arm-none-eabi/include/machine/stdlib.h
> arm-none-eabi/include/stdlib.h
>
> Where did you get the 6.2.0 version?

From the Arch repository:
```
community/arm-none-eabi-gcc 6.2.0-1 [installed]
    The GNU Compiler Collection - cross compiler for ARM EABI (bare-metal) target
```
```
/usr/arm-none-eabi/include/stdlib.h
/usr/arm-none-eabi/include/c++/6.2.0/stdlib.h
/usr/arm-none-eabi/include/c++/6.2.0/tr1/stdlib.h
/usr/arm-none-eabi/include/machine/stdlib.h
```

**Comment by kYc0o** [comment]
I ran that test yesterday with success. Here my compiler:

```
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.2.1 20151202 (release) [ARM/embedded-5-branch revision 231848]
```

**Comment by josephnoir** [comment]
Works with version 5.4 as well. Can't find version 6 for macOS. Could that be a compiler bug?

**Comment by josephnoir** [comment]
Maybe @gebart has the right compiler and can reproduce this?

**Comment by A-Paul** [comment]
From [GNU ARM Embedded Toolchain](https://launchpad.net/gcc-arm-embedded):

> 6.0 series is the current focus of development.

Maybe it's advisable to use a *stable* toolchain for RIOT development. ;)

**Comment by OlegHahm** [comment]
Why do you conclude that 6.2 is *not* stable?

**Comment by OlegHahm** [comment]
And why got this issue renamed?

**Comment by A-Paul** [comment]
> And why got this issue renamed?

I'm not aware of renaming the issue. Sorry, if I did it by accident.

**Comment by miri64** [comment]
I renamed it. I did not think " 01-tests/task 01 Release 2016.10 - RC1" was really helpful

a) because it did not discribe the problem
b) because task 1.1 has nothing to do with arm-none-eabi-g++ (since those are about native)

**Comment by cgundogan** [comment]
@OlegHahm I can reproduce on arch with
```
arm-none-eabi-g++ (Arch Repository) 6.2.0
```

**Comment by cgundogan** [comment]
btw, its also failing for me on native, with:
```
RIOT/sys/cpp11-compat/condition_variable.cpp: In member function ‘void riot::condition_variable::wait(riot::unique_lock<riot::mutex>&)’:
RIOT/sys/cpp11-compat/condition_variable.cpp:84:26: error: throw will always call terminate() [-Werror=terminate]
       "Mutex not locked.");
```

**Comment by josephnoir** [comment]
@cgundogan Are you using gcc 6.something on native as well?

**Comment by cgundogan** [comment]
@josephnoir `g++ (GCC) 6.2.1 20160830`

**Comment by cgundogan** [comment]
@josephnoir I also hit that error with `arm-none-eabi-g++`, so it's not just native.

**Comment by OlegHahm** [comment]
Confirmed.
